language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
   - DRF_BULK="djangorestframework-bulk"
   - REST="djangorestframework==3.3.3"
  matrix:
   - DJANGO="django==1.8.13"
   - DJANGO="django==1.9.7"
   - DJANGO="django==1.9.7" LINT=1
install:
 - pip install $DJANGO
 - pip install $REST
 - pip install $DRF_BULK
 - pip install flake8
script:
 - ./runtests.sh
