language: python
python:
 - "2.7"
 - "3.4"
env:
  global:
   - DRF_BULK="djangorestframework-bulk"
   - REST="djangorestframework==3.2.3"
  matrix:
   - DJANGO="django==1.7.10"
   - DJANGO="django==1.8.4"
   - DJANGO="django==1.8.4" LINT=1
install:
 - pip install $DJANGO
 - pip install $REST
 - pip install $DRF_BULK
 - pip install flake8
script:
 - ./runtests.sh
